INSERT INTO productversions (Version, Link) VALUES ('Visit our Facebook', 'https://web.facebook.com/DigiSoftph/');
INSERT INTO productversions (Version, Link) VALUES ('Previous', 'https://digisoftph.com/#myCarousel');
INSERT INTO productversions (Version, Link) VALUES ('Next', 'https://digisoftph.com/#myCarousel');
INSERT INTO productversions (Version, Link) VALUES ('List of Clients', 'https://digisoftph.com/#clients');
INSERT INTO productversions (Version, Link) VALUES ('Release Notes', 'https://digisoftph.com/#change_log');
INSERT INTO productversions (Version, Link) VALUES ('Downloads', 'https://digisoftph.com/#versions');
INSERT INTO productversions (Version, Link) VALUES ('Brochures', 'https://digisoftph.com/#brochure');
INSERT INTO productversions (Version, Link) VALUES ('SIAS', 'https://digisoftph.com/#cl_sias');
INSERT INTO productversions (Version, Link) VALUES ('CARES', 'https://digisoftph.com/#cl_cares');
INSERT INTO productversions (Version, Link) VALUES ('Payroll', 'https://digisoftph.com/#cl_payroll');
INSERT INTO productversions (Version, Link) VALUES ('AMS', 'https://digisoftph.com/#cl_ams');
INSERT INTO productversions (Version, Link) VALUES ('POS', 'https://digisoftph.com/#cl_pos');
INSERT INTO productversions (Version, Link) VALUES ('EMS', 'https://digisoftph.com/#cl_ems');
INSERT INTO productversions (Version, Link) VALUES ('SMS', 'https://digisoftph.com/#cl_sms');
INSERT INTO productversions (Version, Link) VALUES ('LIS', 'https://digisoftph.com/#cl_lis');
INSERT INTO productversions (Version, Link) VALUES ('QUEUE', 'https://digisoftph.com/#cl_queue');
INSERT INTO productversions (Version, Link) VALUES ('ASIS', 'https://digisoftph.com/#cl_asis');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Online 3.7.2.9 (Released: February 12, 2026)', 'https://digisoftph.com/downloads/siasonline3.7.2.9-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Upgrade 3.7.2.5 (Released: February 10, 2026)', 'https://digisoftph.com/downloads/siasupgrade3.7.2.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Upgrade 3.7.1.29 (Released: January 31, 2026)', 'https://digisoftph.com/downloads/siasupgrade3.7.1.29-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('SIAS SFX 3.7.1.13 (Released: January 13, 2026)', 'https://digisoftph.com/downloads/siassfx3.7.1.13.rar');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Setup 2.7.2.8 (Released: August 29, 2012)', 'https://digisoftph.com/downloads/siassetup2.7.2.8.exe');
INSERT INTO productversions (Version, Link) VALUES ('CARES Online 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/caresonline3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/caresupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Cares WebEms SFX 3.5.9.3 (Released: September 6, 2024)', 'https://digisoftph.com/downloads/careswebems3.5.9.3.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.5.5.26 (Released: July 28, 2024)', 'https://digisoftph.com/downloads/caresupgrade3.5.5.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.5.4.14 (Released: April 28, 2024)', 'https://digisoftph.com/downloads/caresupgrade3.5.4.14-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.4.12.3 (Released: December 5, 2023)', 'https://digisoftph.com/downloads/caresupgrade3.4.12.3-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.4.11.9 (Released: November 30, 2023)', 'https://digisoftph.com/downloads/caresupgrade3.4.11.9-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Cares WebEms 3.4.9.13 (Released: September 24, 2023)', 'https://digisoftph.com/downloads/CaresWebEms3.4.9.13-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Cares WebIDWriter SFX 3.4.9.13 (Released: September 24, 2023)', 'https://digisoftph.com/downloads/CaresIDWriter3.4.9.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('Cares WebIDWriter 3.4.9.13 (Released: September 24, 2023)', 'https://digisoftph.com/downloads/CaresIDWriter3.4.9.13-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.4.9.13 (Released: September 24, 2023)', 'https://digisoftph.com/downloads/caresupgrade3.4.9.13-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.4.8.16 (Released: August 24, 2023)', 'https://digisoftph.com/downloads/caresupgrade3.4.8.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.4.4.4 (Released: April 6, 2023)', 'https://digisoftph.com/downloads/caresupgrade3.4.4.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES Upgrade 3.4.3.2 (Released: March 5, 2023)', 'https://digisoftph.com/downloads/caresupgrade3.4.3.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES POS Online 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/caresposonline3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('CARES POS Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/caresposupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Cares WebPOS SFX 3.4.9.13 (Released: September 24, 2023)', 'https://digisoftph.com/downloads/careswebpos3.4.9.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('Cares WebPOS 3.4.9.13 (Released: September 24, 2023)', 'https://digisoftph.com/downloads/CaresWebPos3.4.9.13-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Web Reader Client SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/webreader3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('Web Reader Client 3.3.15.16 (Released: February 15, 2022)', 'https://digisoftph.com/downloads/webreader3.3.15.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Information Kiosk SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/WebInfo3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Information Kiosk 3.4.9.12 (Released: September 20, 2023)', 'https://digisoftph.com/downloads/WebInfo3.4.9.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Online 3.6.10.9 (Released: October 8, 2025)', 'https://digisoftph.com/downloads/payrollonline3.6.10.9-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.6.10.9 (Released: October 8, 2025)', 'https://digisoftph.com/downloads/payrollupgrade3.6.10.9-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.6.4.3 (Released: April 3, 2025)', 'https://digisoftph.com/downloads/payrollupgrade3.6.4.3-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.6.3.1 (Released: March 3, 2025)', 'https://digisoftph.com/downloads/payrollupgrade3.6.3.1-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.6.2.1 (Released: February 1, 2025)', 'https://digisoftph.com/downloads/payrollupgrade3.6.2.1-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.5.12.11 (Released: December 12, 2024)', 'https://digisoftph.com/downloads/payrollupgrade3.5.12.11-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.5.10.23 (Released: October 26, 2024)', 'https://digisoftph.com/downloads/payrollupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.5.7.16 (Released: July 26, 2024)', 'https://digisoftph.com/downloads/payrollupgrade3.5.7.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.5.4.14 (Released: April 28, 2024)', 'https://digisoftph.com/downloads/payrollupgrade3.5.4.14-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.5.3.2 (Released: March 14, 2024)', 'https://digisoftph.com/downloads/payrollupgrade3.5.3.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.4.9.13 (Released: September 26, 2023)', 'https://digisoftph.com/downloads/payrollupgrade3.4.9.13-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.4.8.16 (Released: August 24, 2023)', 'https://digisoftph.com/downloads/payrollupgrade3.4.8.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.4.4.4 (Released: April 6, 2023)', 'https://digisoftph.com/downloads/payrollupgrade3.4.4.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.4.3.2 (Released: March 5, 2023)', 'https://digisoftph.com/downloads/payrollupgrade3.4.3.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.22.3 (Released: November 23, 2022)', 'https://digisoftph.com/downloads/payrollupgrade3.3.22.3-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.15.35 (Released: March 10, 2022)', 'https://digisoftph.com/downloads/payrollupgrade3.3.15.35-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.14.39 (Released: December 6, 2021)', 'https://digisoftph.com/downloads/payrollupgrade3.3.14.39-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.12.2 (Released: May 25, 2021)', 'https://digisoftph.com/downloads/payrollupgrade3.3.12.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.11.86 (Released: April 22, 2021)', 'https://digisoftph.com/downloads/payrollupgrade3.3.11.86-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.10.83 (Released: October 18, 2020)', 'https://digisoftph.com/downloads/payrollupgrade3.3.10.83-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.8.15 (Released: April 10, 2020)', 'https://digisoftph.com/downloads/payrollupgrade3.3.8.15-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.7.29 (Released: February 16, 2020)', 'https://digisoftph.com/downloads/payrollupgrade3.3.7.29-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.6.8 (Released: June 14, 2019)', 'https://digisoftph.com/downloads/payrollupgrade3.3.6.8-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.5.18 (Released: April 23, 2019)', 'https://digisoftph.com/downloads/payrollupgrade3.3.5.18-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.4.6 (Released: January 23, 2019)', 'https://digisoftph.com/downloads/payrollupgrade3.3.4.6-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.3.1.18 (Released: July 11, 2017)', 'https://digisoftph.com/downloads/payrollupgrade3.3.1.18-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.2.9.7 (Released: December 26, 2017)', 'https://digisoftph.com/downloads/payrollupgrade3.2.9.7-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.2.6.14 (Released: April 2, 2017)', 'https://digisoftph.com/downloads/payrollupgrade3.2.6.14-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.2.5.24 (Released: January 15, 2017)', 'https://digisoftph.com/downloads/payrollupgrade3.2.5.24-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.2.4.7 (Released: September 25, 2016)', 'https://digisoftph.com/downloads/payrollpatch3.2.4.7-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Upgrade 3.2.3.16 (Released: June 27, 2016)', 'https://digisoftph.com/downloads/payrollpatch3.2.3.16-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Online 3.7.1.6 (Released: January 7, 2026)', 'https://digisoftph.com/downloads/amsonline3.7.1.6-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.7.1.6 (Released: January 7, 2026)', 'https://digisoftph.com/downloads/amsupgrade3.7.1.6-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.6.10.7 (Released: October 7, 2025)', 'https://digisoftph.com/downloads/amsupgrade3.6.10.7-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.5.11.5 (Released: November 10, 2024)', 'https://digisoftph.com/downloads/amsupgrade3.5.11.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/amsupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS SFX 3.5.9.2 (Released: September 5, 2023)', 'https://digisoftph.com/downloads/amssfx3.5.9.2.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebAMS Client SFX 3.5.7.16 (Released: July 27, 2024)', 'https://digisoftph.com/downloads/webams3.5.7.16.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.5.5.26 (Released: July 26, 2024)', 'https://digisoftph.com/downloads/amsupgrade3.5.5.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.5.4.14 (Released: April 28, 2024)', 'https://digisoftph.com/downloads/amsupgrade3.5.4.14-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.5.3.7 (Released: March 19, 2024)', 'https://digisoftph.com/downloads/amsupgrade3.5.3.7-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.4.10.10 (Released: October 30, 2023)', 'https://digisoftph.com/downloads/amsupgrade3.4.10.10-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.4.4.5 (Released: April 7, 2023)', 'https://digisoftph.com/downloads/amsupgrade3.4.4.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebAMS Client 3.3.15.12 (Released: February 9, 2022)', 'https://digisoftph.com/downloads/webams3.3.15.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.15.12 (Released: February 9, 2022)', 'https://digisoftph.com/downloads/amsupgrade3.3.15.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.12.2 (Released: May 26, 2021)', 'https://digisoftph.com/downloads/amsupgrade3.3.12.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.11.18 (Released: January 17, 2021)', 'https://digisoftph.com/downloads/amsupgrade3.3.11.18-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.10.83 (Released: October 18, 2020)', 'https://digisoftph.com/downloads/amsupgrade3.3.10.83-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.8.15 (Released: April 10, 2020)', 'https://digisoftph.com/downloads/amsupgrade3.3.8.15-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.7.28 (Released: January 21, 2020)', 'https://digisoftph.com/downloads/amsupgrade3.3.7.28-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.6.7 (Released: May 25, 2019)', 'https://digisoftph.com/downloads/amsupgrade3.3.6.7-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.5.19 (Released: May 7, 2019)', 'https://digisoftph.com/downloads/amsupgrade3.3.5.19-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.3.4.26 (Released: March 16, 2019)', 'https://digisoftph.com/downloads/amsupgrade3.3.4.26.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.2.8.1 (Released: July 31, 2017)', 'https://digisoftph.com/downloads/amsupgrade3.2.8.1.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.2.6.7 (Released: March 17, 2017)', 'https://digisoftph.com/downloads/amsupgrade3.2.6.7.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.2.5.19 (Released: December 24, 2016)', 'https://digisoftph.com/downloads/amsupgrade3.2.5.19.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebAMS Server 3.2.5.9 (Online/Realtime) (Released: November 3, 2016)', 'https://digisoftph.com/downloads/webamsserver3.2.5.9-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Client 3.2.5.2 (LAN) (Released: October 30, 2016)', 'https://digisoftph.com/downloads/amsdtr3.2.5.2-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.2.4.7 (Released: September 25, 2016)', 'https://digisoftph.com/downloads/amsupgrade3.2.4.7.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.2.3.13 (Released: May 4, 2016)', 'https://digisoftph.com/downloads/amsupgrade3.2.3.13.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.2.2.7 (Released: March 15, 2016)', 'https://digisoftph.com/downloads/amsupgrade3.2.2.7.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 3.1.1.1 (Released: January 31, 2016)', 'https://digisoftph.com/downloads/amsupgrade3.1.1.1.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 2.7.3.2 (Released: November 25, 2015)', 'https://digisoftph.com/downloads/amsupgrade2.7.3.2.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Upgrade 2.7.2.8 (Released: July 26, 2014)', 'https://digisoftph.com/downloads/amsupgrade2.7.2.8.rar');
INSERT INTO productversions (Version, Link) VALUES ('AMS Setup 2.6.9.20 (Released: May 14, 2012)', 'https://digisoftph.com/downloads/ams-setup2.6.9.20.exe');
INSERT INTO productversions (Version, Link) VALUES ('WebQueue Client SFX 3.6.8.12 (Released: August 22, 2025)', 'https://digisoftph.com/downloads/WebQueue3.6.8.12.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('WebQueue Client 3.6.8.12 (Released: August 22, 2025)', 'https://digisoftph.com/downloads/WebQueue3.6.8.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Online 3.5.11.5 (Released: November 10, 2024)', 'https://digisoftph.com/downloads/QueueOnline3.5.11.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.5.11.5 (Released: November 10, 2024)', 'https://digisoftph.com/downloads/QueueUpgrade3.5.11.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/QueueUpgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.5.5.26 (Released: July 20, 2024)', 'https://digisoftph.com/downloads/QueueUpgrade3.5.5.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.5.4.14 (Released: April 28, 2024)', 'https://digisoftph.com/downloads/QueueUpgrade3.5.4.14-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.4.7.3 (Released: July 11, 2023)', 'https://digisoftph.com/downloads/QueueUpgrade3.4.7.3-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.4.5.9 (Released: May 27, 2023)', 'https://digisoftph.com/downloads/QueueUpgrade3.4.5.9-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.4.4.5 (Released: April 8, 2023)', 'https://digisoftph.com/downloads/QueueUpgrade3.4.4.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.3.10.83 (Released: October 18, 2020)', 'https://digisoftph.com/downloads/QueueUpgrade3.3.10.83-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.3.8.15 (Released: April 10, 2020)', 'https://digisoftph.com/downloads/QueueUpgrade3.3.8.15-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.3.7.11 (Released: September 11, 2019)', 'https://digisoftph.com/downloads/QueueUpgrade3.3.7.11-net472.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.3.6.7 (Released: May 25, 2019)', 'https://digisoftph.com/downloads/QueueUpgrade3.3.6.7-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.2.8.17 (Released: September 30, 2017)', 'https://digisoftph.com/downloads/QueueUpgrade3.2.8.17-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Upgrade 3.2.7.28 (Released: June 28, 2017)', 'https://digisoftph.com/downloads/WebQueueUpgrade3.2.7.28-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Add User 3.2.4.39 (Released: October 21, 2016)', 'https://digisoftph.com/downloads/MySQLAddUser-Queue-3.2.4.39.rar');
INSERT INTO productversions (Version, Link) VALUES ('Queue Server Patch 3.2.3.11 (Released: July 1, 2016)', 'https://digisoftph.com/downloads/WebQueueServerPatch3.2.3.11-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Online 3.6.9.26 (Released: September 27, 2025)', 'https://digisoftph.com/downloads/posonline3.6.9.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.6.9.26 (Released: September 27, 2025)', 'https://digisoftph.com/downloads/posupgrade3.6.9.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.6.8.10 (Released: August 17, 2025)', 'https://digisoftph.com/downloads/posupgrade3.6.8.10-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.5.11.5 (Released: November 10, 2024)', 'https://digisoftph.com/downloads/posupgrade3.5.11.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/posupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebPOS Client SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/webpos3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.5.5.26 (Released: July 20, 2024)', 'https://digisoftph.com/downloads/posupgrade3.5.5.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.5.4.14 (Released: April 28, 2024)', 'https://digisoftph.com/downloads/posupgrade3.5.4.14-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebPOS Client 3.4.10.2 (Released: October 5, 2023)', 'https://digisoftph.com/downloads/webpos3.4.10.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.4.8.16 (Released: August 24, 2023)', 'https://digisoftph.com/downloads/posupgrade3.4.8.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.4.4.4 (Released: April 6, 2023)', 'https://digisoftph.com/downloads/posupgrade3.4.4.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.4.3.2 (Released: March 5, 2023)', 'https://digisoftph.com/downloads/posupgrade3.4.3.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.22.3 (Released: December 3, 2022)', 'https://digisoftph.com/downloads/posupgrade3.3.22.3-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.12.2 (Released: May 25, 2020)', 'https://digisoftph.com/downloads/posupgrade3.3.12.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.10.83 (Released: October 18, 2020)', 'https://digisoftph.com/downloads/posupgrade3.3.10.83-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.8.15 (Released: April 10, 2020)', 'https://digisoftph.com/downloads/posupgrade3.3.8.15-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.7.28 (Released: January 21, 2020)', 'https://digisoftph.com/downloads/posupgrade3.3.7.28-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.4.23 (Released: March 12, 2019)', 'https://digisoftph.com/downloads/posupgrade3.3.4.23-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.3.1.18 (Released: July 11, 2018)', 'https://digisoftph.com/downloads/posupgrade3.3.1.18-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.2.9.20 (Released: February 16, 2018)', 'https://digisoftph.com/downloads/posupgrade3.2.9.20-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('POS Upgrade 3.2.8.24 (Released: November 11, 2017)', 'https://digisoftph.com/downloads/posupgrade3.2.8.24-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Online 3.6.2.17 (Released: February 21, 2025)', 'https://digisoftph.com/downloads/lisonline3.6.2.17-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.6.2.17 (Released: February 21, 2025)', 'https://digisoftph.com/downloads/lisupgrade3.6.2.17-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.5.11.12 (Released: November 19, 2024)', 'https://digisoftph.com/downloads/lisupgrade3.5.11.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/lisupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS EMS Client SFX 3.5.9.3 (Released: September 6, 2024)', 'https://digisoftph.com/downloads/liswebems3.5.9.3.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('LIS ID Writer Client SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/lisidwriter3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('WebLIS Client SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/weblis3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.5.5.26 (Released: April 28, 2024)', 'https://digisoftph.com/downloads/lisupgrade3.5.5.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.5.4.14 (Released: April 25, 2024)', 'https://digisoftph.com/downloads/lisupgrade3.5.4.14-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.5.2.12 (Released: February 20, 2024)', 'https://digisoftph.com/downloads/lisupgrade3.5.2.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebLIS Client 3.5.2.11 (Released: February 20, 2024)', 'https://digisoftph.com/downloads/weblis3.5.2.11-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS EMS Client 3.5.2.11 (Released: February 20, 2024)', 'https://digisoftph.com/downloads/liswebems3.5.2.11-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS ID Writer Client 3.5.2.11 (Released: February 20, 2024)', 'https://digisoftph.com/downloads/lisidwriter3.5.2.11-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.4.12.4 (Released: December 17, 2023)', 'https://digisoftph.com/downloads/lisupgrade3.4.12.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.4.11.8 (Released: November 24, 2023)', 'https://digisoftph.com/downloads/lisupgrade3.4.11.8-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.4.10.8 (Released: October 20, 2023)', 'https://digisoftph.com/downloads/lisupgrade3.4.10.8-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.4.8.16 (Released: August 24, 2023)', 'https://digisoftph.com/downloads/lisupgrade3.4.8.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.4.4.4 (Released: April 6, 2023)', 'https://digisoftph.com/downloads/lisupgrade3.4.4.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.4.3.2 (Released: March 5, 2023)', 'https://digisoftph.com/downloads/lisupgrade3.4.3.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.22.4 (Released: November 11, 2022)', 'https://digisoftph.com/downloads/lisupgrade3.3.22.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.15.12 (Released: February 7, 2022)', 'https://digisoftph.com/downloads/lisupgrade3.3.15.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.12.2 (Released: May 25, 2021)', 'https://digisoftph.com/downloads/lisupgrade3.3.12.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.10.83 (Released: October 18, 2020)', 'https://digisoftph.com/downloads/lisupgrade3.3.10.83-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.8.15 (Released: April 10, 2020)', 'https://digisoftph.com/downloads/lisupgrade3.3.8.15-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.7.28 (Released: January 21, 2020)', 'https://digisoftph.com/downloads/lisupgrade3.3.7.28-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.6.7 (Released: June 12, 2019)', 'https://digisoftph.com/downloads/lisupgrade3.3.6.7-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.3.15 (Released: November 27, 2018)', 'https://digisoftph.com/downloads/lisupgrade3.3.3.15-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.3.1.18 (Released: July 11, 2018)', 'https://digisoftph.com/downloads/lisupgrade3.3.1.18-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('LIS Upgrade 3.2.8.15 (Released: September 28, 2017)', 'https://digisoftph.com/downloads/lisupgrade3.2.8.15-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Online 3.6.2.23 (Released: February 27, 2025)', 'https://digisoftph.com/downloads/asisonline3.6.2.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.5.11.5 (Released: November 10, 2024)', 'https://digisoftph.com/downloads/asisupgrade3.5.11.5-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.5.10.23 (Released: October 27, 2024)', 'https://digisoftph.com/downloads/asisupgrade3.5.10.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.5.5.26 (Released: May 24, 2024)', 'https://digisoftph.com/downloads/asisupgrade3.5.5.26-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.5.4.11 (Released: April 20, 2024)', 'https://digisoftph.com/downloads/asisupgrade3.5.4.11-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.4.10.8 (Released: October 26, 2023)', 'https://digisoftph.com/downloads/asisupgrade3.4.10.8-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.4.8.16 (Released: August 24, 2023)', 'https://digisoftph.com/downloads/asisupgrade3.4.8.16-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.4.4.4 (Released: April 6, 2023)', 'https://digisoftph.com/downloads/asisupgrade3.4.4.4-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.4.3.2 (Released: March 5, 2023)', 'https://digisoftph.com/downloads/asisupgrade3.4.3.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.3.22.3 (Released: December 6, 2022)', 'https://digisoftph.com/downloads/asisupgrade3.3.22.3-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.3.12.2 (Released: May 26, 2021)', 'https://digisoftph.com/downloads/asisupgrade3.3.12.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.3.10.83 (Released: October 18, 2020)', 'https://digisoftph.com/downloads/asisupgrade3.3.10.83-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.3.8.15 (Released: April 10, 2020)', 'https://digisoftph.com/downloads/asisupgrade3.3.8.15-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('ASIS Upgrade 3.3.7.30 (Released: February 11, 2020)', 'https://digisoftph.com/downloads/asisupgrade3.3.7.30-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebEMS Client SFX 3.7.1.17 (Released: January 18, 2026)', 'https://digisoftph.com/downloads/webems3.7.1.17.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('WebEMS Client 3.7.1.17 (Released: January 18, 2026)', 'https://digisoftph.com/downloads/webems3.7.1.17-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('EMS Server 3.6.2.23 (Released: February 27, 2025)', 'https://digisoftph.com/downloads/emsonline3.6.2.23-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('WebSMS Client SFX 3.4.12.2 (Released: December 4, 2023)', 'https://digisoftph.com/downloads/websms3.4.12.2.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('WebSMS Client 3.4.12.2 (Released: December 4, 2023)', 'https://digisoftph.com/downloads/websms3.4.12.2-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Application Launcher 3.3.6.3 (Released: May 16, 2019)', 'https://digisoftph.com/downloads/Launcher3.3.6.3-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('Web ID Writer Client SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/webidwriter3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('Web ID Writer Client 3.4.9.12 (Released: September 21, 2023)', 'https://digisoftph.com/downloads/webidwriter3.4.9.12-net48.rar');
INSERT INTO productversions (Version, Link) VALUES ('Visitor ID Writer Client SFX 3.5.7.13 (Released: July 23, 2024)', 'https://digisoftph.com/downloads/visitoridwriter3.5.7.13.sfx.exe');
INSERT INTO productversions (Version, Link) VALUES ('Visitor ID Writer Client 3.3.10.83 (Released: October 19, 2020)', 'https://digisoftph.com/downloads/visitoridwriter3.3.10.83-net45.rar');
INSERT INTO productversions (Version, Link) VALUES ('List of Clients', 'https://digisoftph.com/downloads/List%20of%20Clients.pdf');
INSERT INTO productversions (Version, Link) VALUES ('SIAS3 Cover Letter for Private Schools', 'https://digisoftph.com/downloads/SIAS3%20-%20Cover%20Letter%20-%20Private%20Schools.docx');
INSERT INTO productversions (Version, Link) VALUES ('SIAS3 Cover Letter for SUCs', 'https://digisoftph.com/downloads/SIAS3%20-%20Cover%20Letter%20-%20SUCs.docx');
INSERT INTO productversions (Version, Link) VALUES ('Front Page', 'https://digisoftph.com/downloads/SIAS3%20-%20Front%20Page.pdf');
INSERT INTO productversions (Version, Link) VALUES ('DigiSoft SIAS Presentation (Powerpoint)', 'https://digisoftph.com/downloads/DigiSoft%20SIAS%20Presentation.pptx');
INSERT INTO productversions (Version, Link) VALUES ('DigiSoft SIAS Presentation (PDF)', 'https://digisoftph.com/downloads/DigiSoft%20SIAS%20Presentation.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Why SIAS Online 3.x the FASTEST? Caching Technology (PDF)', 'https://digisoftph.com/downloads/Why%20SIAS%20Online%203.x%20the%20FASTEST%20-%20Caching%20Technology.pdf');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Online 3.x Features', 'https://digisoftph.com/downloads/SIAS%20Online%203.x%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('SIAS-LMS (Learning Management System) Online 3.x Features', 'https://digisoftph.com/downloads/SIAS-LMS%20Onliine%203.x%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Desktop 3.x Features for Private Schools', 'https://digisoftph.com/downloads/SIAS%20Desktop%203.x%20Features%20-%20Private%20Schools.pdf');
INSERT INTO productversions (Version, Link) VALUES ('SIAS Desktop 3.x Features for SUCs', 'https://digisoftph.com/downloads/SIAS%20Desktop%203.x%20Features%20-%20SUCs.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Payroll Online 3.x Features', 'https://digisoftph.com/downloads/Payroll%20Online%203.x%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('AMS 3.x Features', 'https://digisoftph.com/downloads/AMS3%20-%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Online Library Information System 3.x Features', 'https://digisoftph.com/downloads/LIS3%20-%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Hardware and Features', 'https://digisoftph.com/downloads/webQueue%20Hardware%20and%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Brochure (Front)', 'https://digisoftph.com/downloads/WebQueue-Brochure-Front.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Brochure (Back)', 'https://digisoftph.com/downloads/WebQueue-Brochure-Back.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Reservation Kiosk', 'https://digisoftph.com/downloads/WebQueue-Reservation.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Display TV at Cashier''s Office (Name Displayed)', 'https://digisoftph.com/downloads/WebQueue-Display-Cashier-DisplayName.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Display TV at Cashier''s Office (No name column)', 'https://digisoftph.com/downloads/WebQueue-Display-Cashier-HideName.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Dual Biometric/Smartcard Touch Screen Kiosk', 'https://digisoftph.com/downloads/Biometric%20Kiosk%20-%20Small.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Viewing Grades', 'https://digisoftph.com/downloads/Student-Grades-Hidden.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Viewing Statement of Accounts', 'https://digisoftph.com/downloads/Student-Statement%20of%20Accounts-Hidden.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Get a Paperless Queue No', 'https://digisoftph.com/downloads/Student-Getting%20a%20Queue%20No-Hidden.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Entry Monitoring System 3.x Features', 'https://digisoftph.com/downloads/Entry%20Monitoring%20System%203.x%20Features.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Flap Barrier Turnstile Specifications and Features', 'https://digisoftph.com/downloads/Flap%20Barrier%20Turnstile%20Specifications.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Fully Automatic Flap Barrier (Actual Pic 1)', 'https://digisoftph.com/downloads/Namiton-CNT-YW120TY-Flap-Barrier-1.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Fully Automatic Flap Barrier (Actual Pic 2)', 'https://digisoftph.com/downloads/Namiton-CNT-YW120TY-Flap-Barrier-2.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Tripod Turnstile Specifications and Features', 'https://digisoftph.com/downloads/Tripod%20Turnstile%20Specifications.pdf');
INSERT INTO productversions (Version, Link) VALUES ('Turnstile Fully-Automatic Front (Actual Pic)', 'https://digisoftph.com/downloads/Turnstile-Fully-Automatic-Front.jpg');
INSERT INTO productversions (Version, Link) VALUES ('Turnstile Fully-Automatic Back (Actual Pic)', 'https://digisoftph.com/downloads/Turnstile-Fully-Automatic-Back.jpg');
INSERT INTO productversions (Version, Link) VALUES ('shoutsofdavid', 'http://www.facebook.com/erwildavid.pasion');
